travis:
  secure:
    BINSTAR_TOKEN: yScYbG2593MLr9xQeogyoRZj/DLdOgGXF3vSxBAR+eZNF9ZB23Kd3n4Cp16Qe9rYmMmVDgwPX+iSGfc9qIxNubkwB+ZGIN01MUSaOfpe+03sJqcPPtCy9GHstovH0pOs/pYr4GV2M5e6+tahVuURezR9YHfkhoO0N1UGPsBn/6hqTzktD2ansUgKjlhd4kxFtB6N74zPfgq/pXFed5yVfx2JYOsRLUaIDOhkOGG2UnsdCGaeIP5NeP5e0qFjSc9OSRW0iptdRXmHUvf6N4mCgQoFIRXpX0YWR+Nk2Vke7AMouie8vA7eW2N+ZGnEahiouhqf8KTtwxdV3DoeSaG858kuDUx5DBVzdPyoNNrjfu3rgp/Qv4vcLTA5NQQ5h9VX5tdSGoCitnKQMODBiCAvRk61TTSyRDUi6c//k4LBElC0CV2iPurdjTu8Ez/TulzfniIRhiPqYcnLP3CYC3ZuKRCxrVzwMb5PB/tvkXnBtIlPc9ZQFsoNyAWkvU91+Wjqex3fvazOerIVfnx0l940n2ZFKYjlRxit1jt/p1Q9X7QliwL2cvQGGb5x5in/1TyDPY0Q4YqPIAxR2SLIju1nlFVcs3hOP5UBk5XpvyQu2pQMI8o5wptnvhq5gRhLk2r8tzEbFvAxclGtMdoZryf2nJOvxOIrGJFDE6QBG8r74T4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
